% Class 
\ProvidesClass{resume-class}[2020/03/20 CV class]
\LoadClass{article}
\NeedsTeXFormat{LaTeX2e}


\RequirePackage{}
\usepackage{fontawesome5} % Font Awesome


% Page settings
\usepackage[left=0.75in,top=0.6in,right=0.75in,bottom=0.6in]{geometry}
\RequirePackage{hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,      
    urlcolor=cyan,
    pdftitle=Resume of Osman F. Bayram,
    pdfauthor=Osman F. Bayram,
    pdfpagemode=FullScreen,
}
\renewcommand{\familydefault}{\sfdefault}
