on:
  push:
    branches:
    - main
    
    
jobs:
  build-pdf:
    name: Build the pdf using pdflatex
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: dante-ev/latex-action@latest
        with:
          latex_command: pdflatex
          latex_options: main.tex

      - uses: actions/upload-artifact@v1
        with:
          artifact_path: main.pdf
          artifact_name: main.pdf
          artifact_target_path: /
          artifact_target_name: main.pdf
          artifact_target_url: