on:
  push:
    branches:
    - main
    
    
jobs:
  build-pdf:
    name: Build the pdf using pdflatex
    runs-on: ubuntu-latest
    
    steps:
      - uses: dante-ev/latex-action@latest
      - name: Run latex
      - uses: dante-ev/latex-action@latest
        with:
          latex_command: pdflatex
          latex_options:
          - "-interaction=nonstopmode"
          - "-output-directory=build"
          - "-jobname=main"
          - "main.tex"