name: Build and upload the resume
on:
  push:
    branches:
    - main
    
    
jobs:
  build-pdf:
#    name: Build the pdf using pdflatex
    runs-on: ubuntu-latest
    
    steps:
      - name: Check this out
        uses: actions/checkout@v2
        
      - name: Build the latex file
      - uses: dante-ev/latex-action@latest
        with:
          latex_command: pdflatex
          latex_options: main.tex

      - name: Upload the artifact
        uses: actions/upload-artifact@v1
        with:
          name: main.pdf
          path: main.pdf

