on:
  push:
    branches:
    - main
    
    
jobs:
  build-pdf:
    name: Build the pdf using pdflatex
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Is it working?
      run: |
        ls
        echo test
