name: Build the pdf

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-pdf-job:
    name: Build the pdf using pdflatex
    runs-on: ubuntu-latest

    steps:
      - name: Check this out
        uses: actions/checkout@v2

      - name: Build the latex file
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          compiler: xelatex

      - name: Upload the artifact
        uses: actions/upload-artifact@v1
        with:
          name: resume
          path: resume.pdf

      - name: Move files to the publish directory
        run: mkdir github_deploy && mv resume.pdf github_deploy/resume.pdf

      - name: Deploy the pdf file
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
